Repository romi/plant-3d-vision, pull requests merged in 2020-06, with the labels that each got.

#47 Clean Dockerfile
  docker/Dockerfile
Labels: Chore

#52 Add modifications induced by renaming consistently some repos
  README.md
  docker/Dockerfile
Labels: Chore

#53 Fix cgal package name
  romiscan/proc3d.py
Labels: refactoring

#57 Fix/aws dockerfile
  README.md
  docker/Dockerfile
Labels: bug

#60 Fix/backprojection
  romiscan/cl.py
  romiscan/proc3d.py
Labels: bug

#66 Refactoring/romi run task
  bin/romi_run_task
  setup.py
Labels: Chore, enhancement

#62 A better colmap runner
  romiscan/colmap.py
Labels: enhancement

#68 Fix/config file ml
  config/ml_pipe_real_2.toml
  config/ml_pipe_vplants_4.toml
Labels: bug
